import { useState, useRef, type KeyboardEvent } from 'react';
import { CheckCircle2, MessageCircle, Send, Sparkles } from 'lucide-react';
import type { FollowUpQuestion } from '@/types';

interface AIQuestionsProps {
  questions: FollowUpQuestion[];
  onRespond: (questionId: string, response: string) => void;
}

/**
 * AIQuestions displays follow-up questions generated by the AI assistant.
 * Each question appears as a conversational card with an inline response input.
 * Answered questions show the nurse's response and dim to indicate completion.
 *
 * Requirements: 4.1, 4.2, 4.3, 4.4
 */
export function AIQuestions({ questions, onRespond }: AIQuestionsProps) {
  if (questions.length === 0) return null;

  return (
    <section aria-label="Follow-up questions from AI assistant">
      {/* Section heading */}
      <div className="flex items-center gap-2 mb-4">
        <Sparkles className="w-4 h-4 text-indigo-500" aria-hidden="true" />
        <h3 className="text-sm font-semibold text-slate-700">
          Follow-up Questions
        </h3>
      </div>

      {/* Question cards */}
      <div className="space-y-3">
        {questions.map((question) => (
          <QuestionCard
            key={question.id}
            question={question}
            onRespond={onRespond}
          />
        ))}
      </div>
    </section>
  );
}

// --- Individual question card ---

interface QuestionCardProps {
  question: FollowUpQuestion;
  onRespond: (questionId: string, response: string) => void;
}

function QuestionCard({ question, onRespond }: QuestionCardProps) {
  const [inputValue, setInputValue] = useState('');
  const inputRef = useRef<HTMLInputElement>(null);

  const trimmed = inputValue.trim();
  const canSubmit = trimmed.length > 0;

  const handleSubmit = () => {
    if (!canSubmit) return;
    onRespond(question.id, trimmed);
    setInputValue('');
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      e.preventDefault();
      handleSubmit();
    }
  };

  return (
    <div
      className={[
        'rounded-lg border p-3 sm:p-4 transition-all duration-300 animate-in fade-in',
        question.answered
          ? 'bg-slate-50/50 border-slate-100 opacity-80'
          : 'bg-white border-slate-100 shadow-sm',
      ].join(' ')}
    >
      {/* Question row */}
      <div className="flex items-start gap-3">
        {/* Icon */}
        <span className="flex-shrink-0 mt-0.5">
          {question.answered ? (
            <CheckCircle2
              className="w-5 h-5 text-emerald-500"
              aria-hidden="true"
            />
          ) : (
            <MessageCircle
              className="w-5 h-5 text-indigo-500"
              aria-hidden="true"
            />
          )}
        </span>

        {/* Question content */}
        <div className="flex-1 min-w-0">
          <p
            className={[
              'text-sm font-semibold leading-relaxed',
              question.answered ? 'text-slate-500' : 'text-slate-800',
            ].join(' ')}
          >
            {question.question}
          </p>

          {/* Answered: show response */}
          {question.answered && question.response && (
            <p className="mt-2 text-sm text-slate-600 bg-indigo-50/50 rounded-md px-3 py-2">
              {question.response}
            </p>
          )}

          {/* Not answered: show input */}
          {!question.answered && (
            <div className="mt-3">
              <div
                className={[
                  'flex items-center gap-2 border rounded-lg px-3',
                  'bg-white transition-all duration-150',
                  'border-slate-200 focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-1 focus-within:border-indigo-500',
                ].join(' ')}
              >
                <input
                  ref={inputRef}
                  type="text"
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder="Type your response..."
                  aria-label={`Respond to: ${question.question}`}
                  className="flex-1 min-h-[44px] text-sm text-slate-900 placeholder-slate-400 bg-transparent outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:rounded-md"
                />
                <button
                  type="button"
                  onClick={handleSubmit}
                  disabled={!canSubmit}
                  aria-label="Submit response"
                  className={[
                    'flex-shrink-0 flex items-center justify-center',
                    'min-w-[36px] min-h-[36px] w-9 h-9 rounded-md',
                    'transition-all duration-150',
                    !canSubmit
                      ? 'text-slate-300 cursor-not-allowed'
                      : 'text-indigo-600 hover:bg-indigo-50 active:scale-95',
                    'focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-1',
                  ].join(' ')}
                >
                  <Send className="w-4 h-4" aria-hidden="true" />
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
